### ISSUE TITLE
Must load node w/ main first

### ISSUE THREAD

**Issue by fahall** [glumpyfish/godot_redux#1]
Got this setup this evening, and I'm liking it!

I spent the last 30-60min hunting down a bug that boiled down to a little 'gotcha' that I don't see in the documentation. The code in `main.gd` appears to need to be linked to a node and, the bit that gave me trouble, that node needs to be spawned before any nodes that might reference it. 

This may be obvious, or maybe there is a better way to handle it, but that final bit of setup as to how to hook the plugin into a project would be nice to have in the documentation.

**Comment by kennethjeremyau** [comment]
I'm glad it is working out for you!  Yes I need to put in some time to improve the documentation.  Thanks for the issue.
